kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.roleBinding.name }}
subjects:
  - kind: Group
    name: system:serviceaccounts:{{ .Values.namespace }} # All svc accounts of ingress-basic namespaces
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ .Values.roleBinding.roleRefName }} # A references to the role above
  apiGroup: rbac.authorization.k8s.io
