apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    release: {{ .Release.Name | quote }}
type: Opaque
data:
  {{- if not (empty .Values.secrets) }}
  truststore_pass: {{ .Values.secrets.truststore_pass | b64enc | quote }}
  {{- else }}
  truststore_pass: '${#stage("secrets")["context"]["truststore_pass"]}'
  {{- end }}
