apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: {{.Values.serviceAccount.name}}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- $id := .Values.projectId }}
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.annotation | replace "projectId" $id }}
